### PR TITLE
Add Dockerfile and update readme

### PR DESCRIPTION
**Pull request by chris-barry**
Might not be a good idea to merge until it's on dockerhub.

### CODE REVIEW

**Comment by robertfoss** [comment]
Very nice!

Give me a shout when you'd like it merged and I'll merge it.

**Comment by chris-barry** [comment]
Will do

**Comment by chris-barry** [comment]
Wanna merge this? 👍

**Comment by robertfoss** [comment]
Yes!

Sorry about that.

**Comment by chris-barry** [comment]
damn that was fast

**Pull request merged**
